springdoc:
  api-docs:
    path: /policy-search-openapi
    
spring:
  jackson.serialization.indent_output: true
  application:
    name: iss-policy-search-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      discovery:
        all-namespaces: true
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
          auto-add-partitions: true # (*) all services create topic and add partitions
          min-partition-count: 3    # (*)         
        bindings:
          input:
             consumer: 
                auto-commit-offset: false
                ack-each-record: true
      bindings:
        input:
          consumer:
            partitioned: true
            concurrency: 3
          destination: policy-topic
          content-type: application/json # it's redundant here, 'application/json' is the default
          group: eventServiceGroup

elasticsearch:
  clustername: elasticsearch
  host: ${ES_HOST:localhost}
  port: ${ES_PORT:9300}
  repository:
        enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'