spring:
  jackson.serialization.indent_output: true
  application:
    name: iss-policy-search-service
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
          auto-add-partitions: true # (*) all services create topic and add partitions
          min-partition-count: 3    # (*)         
        bindings:
          input:
             consumer: 
                auto-commit-offset: false
                ack-each-record: true
      bindings:
        input:
          destination: POLICY_TOPIC
          content-type: application/json # it's redundant here, 'application/json' is the default
          group: eventServiceGroup

elasticsearch:
     repository:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"